## @file
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8.x"
      architecture: "x64"

  - bash: git clone https://github.com/tianocore/edk2.git $(Build.SourcesDirectory)/edk2
    displayName: Checkout EDK2 repository

  - bash: git clone https://github.com/yabits/9pfsPkg.git $(Build.SourcesDirectory)/edk2/9pfsPkg
    displayName: Checkout 9pfsPkg

  - script: pip install -r pip-requirements.txt --upgrade
    workingDirectory: $(Build.SourcesDirectory)/edk2
    displayName: Install/Upgrade pip modules

  - script: stuart_setup -c .pytool/CISettings.py TOOL_CHAIN_TAG=GCC5
    workingDirectory: $(Build.SourcesDirectory)/edk2
    displayName: Setup

  - script: stuart_update -c .pytool/CISettings.py TOOL_CHAIN_TAG=GCC5
    workingDirectory: $(Build.SourcesDirectory)/edk2
    displayName: Update

  - bash: sudo apt-get update
    displayName: Update apt

  - bash: sudo apt-get install gcc g++ make uuid-dev
    displayName: Install required tools

  - script: python BaseTools/Edk2ToolsBuild.py -t GCC5
    workingDirectory: $(Build.SourcesDirectory)/edk2
    displayName: Build Base Tools from source

  - bash: git apply $(Build.SourcesDirectory)/edk2/9pfsPkg/.azurepipelines/patches/*.patch
    workingDirectory: $(Build.SourcesDirectory)/edk2
    displayName: Apply patches

  - script: stuart_ci_build -c .pytool/CISettings.py TOOL_CHAIN_TAG=GCC5 -p 9pfsPkg -a X64
    workingDirectory: $(Build.SourcesDirectory)/edk2
    displayName: Build and Test

  - task: PublishTestResults@2
    displayName: Publish junit test results
    continueOnError: true
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Build.SourcesDirectory)/edk2/Build/TestSuites.xml
      mergeTestResults: true
      testRunTitle: $(System.JobName)
      publishRunAttachments: true
